### ISSUE TITLE
Hotnode on Windows with CoffeeScript

### ISSUE THREAD

**Issue by sntran** [saschagehlich/hotnode#4]
It gave this error:

``` javascript
$ hotcoffee app.coffee
hotnode: coffee process restarted
CreateProcessW: The system cannot find the file specified.


fs.js:734
    throw new Error('use fs.watch api instead');
          ^
Error: use fs.watch api instead
    at Object.watchFile (fs.js:734:11)
    at Socket.<anonymous> (d:\users\Administrator\AppData\Roaming\npm\node_modules\hot
node\javascript\hotloader.js:81:28)
    at Socket.emit (events.js:88:20)
    at Pipe.onread (net.js:342:31)
```

**Comment by saschagehlich** [comment]
Which version of hotnode / hotcoffee are you using? Try `hotnode -v`

**Comment by sntran** [comment]
v.0.0.6

Running on node v.0.6.10

**Comment by saschagehlich** [comment]
Hey @sntran, sorry for the 6 months delay! Didn't recognize that I actually didn't push the latest version to npm. Could you try running hotnode on Windows again (update hotnode before)? I don't have a Windows machine with node set up over here.

Thanks in advance!
