### ISSUE TITLE
hotnode does not restart on file change

### ISSUE THREAD

**Issue by christowm** [saschagehlich/hotnode#5]
I have written a very simple hello world server.js file. After executing the command "hotnode server.js" from the command line, the server starts and I can access the app from a browser. However any subsequent changes to the server.js file does not restart hotnode automatically. I have to stop hotnode manually and restart it for the changes that I made to the server.js file to take effect. I also tried this with an absolute file path and had the same issue. I am running this environment on ubuntu linux 12.04 LTS. I don't have anything else to go on, since there are no error messages generated or anything else. It seems that hotnode simply does not recognize that the file has changed. Any thoughts on what could be going on?

**Comment by saschagehlich** [comment]
Fixed in v0.0.8 (latest release)
